"""drop created_by_id and posted_by_id attribution columns

Revision ID: 8d86027dbfdf
Revises: 3a3225dd3e0e
Create Date: 2026-02-25 23:42:04.413970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d86027dbfdf'
down_revision: Union[str, None] = '3a3225dd3e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payments_posted_by_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'posted_by_id')
    op.drop_constraint(op.f('reservations_created_by_id_fkey'), 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reservations_created_by_id_fkey'), 'reservations', 'users', ['created_by_id'], ['id'])
    op.add_column('payments', sa.Column('posted_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_posted_by_id_fkey'), 'payments', 'users', ['posted_by_id'], ['id'])
    # ### end Alembic commands ###
